### ISSUE TITLE
gen_fake_sni: ip header is null

### ISSUE THREAD

**Issue by aospiridonov** [Waujito/youtubeUnblock#20] opened 2024-08-02 09:28 UTC
How to fix ?
gen_fake_sni: ip header is null

I'm run with command 
```systemctl enable --now youtubeUnblock.service```
and I have
```
Loaded: loaded (/usr/local/lib/systemd/system/youtubeUnblock.service; enabled; preset: enabled)
     Active: active (running) since Fri 2024-08-02 12:22:24 MSK; 4s ago
    Process: 52698 ExecStartPre=iptables -t mangle -A OUTPUT -p tcp --dport 443 -j NFQUEUE --queue-num 537>
   Main PID: 52703 (youtubeUnblock)
      Tasks: 1 (limit: 38351)
     Memory: 500.0K
        CPU: 4ms
     CGroup: /system.slice/youtubeUnblock.service
             └─52703 /usr/local/bin/youtubeUnblock 537

 02 12:22:24 x570 systemd[1]: Starting youtubeUnblock.service - youtubeUnblock...
 02 12:22:24 x570 systemd[1]: Started youtubeUnblock.service - youtubeUnblock.
 02 12:22:28 x570 youtubeUnblock[52703]: gen_fake_sni: ip header is null: Success
 02 12:22:29 x570 youtubeUnblock[52703]: gen_fake_sni: ip header is null: Success
```

**Comment by Waujito** [comment] 2024-08-02 09:36
Duplicate of #17

**Closed by Waujito** 2024-08-02 09:36 UTC
