### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by cu6apum** [Waujito/youtubeUnblock#21] opened 2024-08-02 13:32 UTC
It looks like my own dumbness, but I cannot track the issue. 
OpenWrt 23.05.4 r24012-d8dd03c46f, kernel 5.15.162, armv8/rockchip.

Rule added to mangle iptable. The binary is being run standalone in terminal.

# /bin/youtubeUnblock 537
Using TCP segmentation
Fake SNI will be sent before each googlevideo request
GSO is enabled
send fake sni
: Operation not permitted
send fake sni
: Operation not permitted

This happens on every request to youtube player from a LAN device.

Thank you!

**Comment by Waujito** [comment] 2024-08-02 13:59
Experiencing it too, #17 and #13 may be helpful.

**Comment by cu6apum** [comment] 2024-08-02 14:10
Setting the queue to postrouting chain didn't help either. If there were any conflicting rules (docker etc), I pruned them by saying -o eth0 (the wan device).

**Comment by eryepa** [comment] 2024-08-02 14:23
> # /bin/youtubeUnblock 537
> Using TCP segmentation Fake SNI will be sent before each googlevideo request GSO is enabled send fake sni : Operation not permitted send fake sni : Operation not permitted

it looks like you are trying to run 2 copies. maybe you started the service and then started the app?

**Comment by Waujito** [comment] 2024-08-02 16:54
> > # /bin/youtubeUnblock 537
> > Using TCP segmentation Fake SNI will be sent before each googlevideo request GSO is enabled send fake sni : Operation not permitted send fake sni : Operation not permitted
> 
> it looks like you are trying to run 2 copies. maybe you started the service and then started the app?

No, the messages are different. If you start the service and the app simultaneously you will get mnl_run error, here the error goes through the rawsocker.

@cu6apum The solution is in #17, further discussion will be there. Closing as duplicate of #17

**Closed by Waujito** 2024-08-02 16:54 UTC
